### ISSUE TITLE
Messages & Read Receipts Repeating Infinitely

### ISSUE THREAD

**Issue by lanerussell** [vector-im/element-android#5690]
### Steps to reproduce

1. Where are you starting? What can you see?
    * Open app
    * Open bugged chat
    * Scroll back through message history
    * See duplicate messages and read receipts

You can see the "Encryption Enabled" message appears multiple times. This is the same for the few messages in the chat, and will repeat infinitely if I keep scrolling.
<details>
<summary>Screenshots</summary>

![screenshot](https://user-images.githubusercontent.com/20979879/161581410-6a79bda1-ae46-4754-9c23-83f471e2889a.png)

![screenshot2](https://user-images.githubusercontent.com/20979879/161581450-ca84b11b-1fee-476c-8175-69d509766d86.png)

</details>

#### What did you expect?
Only 1 copy of each message should appear, only 1 read receipt per user.

#### What happened instead?
Duplicates of both appear.

### Your phone model

Pixel 3

### Operating system version

Android 12

### Application version and app store

1.44 olm 3.2.10 Play Store

### Homeserver

matrix-synapse-py3/unknown,now 1.49.2+bionic1

### Will you send logs?

Yes

**Comment by ganfra** [comment]
Have you tried upgrading your app to the latest version?

**Comment by lanerussell** [comment]
My app has updated to 1.4.8 since this issue was opened, and the issue persists.

**Comment by lanerussell** [comment]
Sure thing. This is the only room I'm seeing this in. This is one of many of my rooms (encrypted and unencrypted) I upgraded to room version 8 around August 2021. I haven't been able to reproduce this bug by creating new rooms. It's interesting that the issue persists after removing the app and setting it back up from scratch.

I'll also include a screenshot from element-web which shows some additional older messages that don't appear on android. Web also shows the link to the old version of the room (which is empty at this point due to homeserver retention policy:
```
retention:
  enabled: true

  default_policy:
    min_lifetime: 1d
    max_lifetime: 90d

  allowed_lifetime_min: 1d
  allowed_lifetime_max: 90d

  purge_jobs:
    - longest_max_lifetime: 3d
      interval: 1h
    - shortest_max_lifetime: 3d
      interval: 1d
```

<details>
<summary>Element Web Screenshot</summary>

![1](https://user-images.githubusercontent.com/20979879/162993819-9d31be76-d7ff-4dec-b879-f3d935c678fd.png)
</details>
