### ISSUE TITLE
Element ask's for mail confirmation on registration, while 3pid not enabled in synapse

### ISSUE THREAD

**Issue by coolsantino** [vector-im/element-android#6968]
### Steps to reproduce

1. Strart synapse without 3pid and email option enabled
2. Start registration process from android
3. At the end of process, elemnt asks to confirm email address

#### What did you expect?
Ability to skip mail verification with no 3pid requirements enabled on the server side

#### What happened instead?
No options, other than go thru process of email address confirmation.

### Your phone model

Any android phone

### Operating system version

Android 12

### Application version and app store

1.4.34

### Homeserver

foilhat.tk

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by ouchadam** [comment]
what is the synapse configuration being used? we have a bug where optional email registration is being treated as mandatory https://github.com/vector-im/element-android/issues/6969, this only occurs when an email delegate has been set

```
account_threepid_delegates:
    email: https://matrix.org
```

**Comment by coolsantino** [comment]
```
server_name: '############'

public_baseurl: '############'

pid_file: /data/homeserver.pid

allow_public_rooms_over_federation: true

listeners:
  - port: 8008
    bind_address: '0.0.0.0'
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation, consent]
        compress: false

max_upload_size: 100M

allow_device_name_lookup_over_federation: true

event_cache_size: 50K

caches:
  global_factor: 10.0
  sync_response_cache_duration: 3m

database:
  name: psycopg2
  args:
    user: ############
    password: ############
    database: ############
    host: ############
    port: 5432
    cp_min: 2
    cp_max: 10

log_config: '############'

media_store_path: '/data/media_store'

dynamic_thumbnails: true

url_preview_enabled: true

url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'

federation_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'

recaptcha_public_key: '############'
recaptcha_private_key: '############'
enable_registration_captcha: true

turn_uris: [############]
turn_shared_secret: '############'
turn_user_lifetime: 24h
turn_allow_guests: false

enable_registration: true
registration_shared_secret: '############'

report_stats: false

macaroon_secret_key: '############'

form_secret: '############'

signing_key_path: '############'

trusted_key_servers:
  - server_name: 'matrix.org'
  - server_name: 'gitter.im'
  - server_name: 'libera.chat'

suppress_key_server_warning: true

media_retention:
  remote_media_lifetime: 30d

user_consent:
  version: 1.0
  template_dir: /data/privacy_policy_templates
  require_at_registration: true
  policy_name: 'Privacy Policy'

email:
  smtp_host: '############'
  smtp_port: 587
  smtp_user: '############'
  smtp_pass: '############'
  enable_tls: true
  require_transport_security: true
  notif_from: '############'
  app_name: '############'
  enable_notifs: false
  notif_for_new_users: false
  client_base_url: '############'
  validation_token_lifetime: 15m
  invite_client_location: '############'
```
