### ISSUE TITLE
Optional email entry is considered mandatory 

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#6969]
### Steps to reproduce

1. With a homeserver with a `mandatory=false` email stage 
2. Attempt to create an account
3. Notice the email address must be entered 

![2022-08-30T14:52:19,484388920+01:00](https://user-images.githubusercontent.com/1848238/187464763-2274494f-b9d9-485e-80a0-3fb51874f20b.png)

Synapse config to enable optional email registration step

with an email delegate

```
account_threepid_delegates:
    email: https://matrix.org
```

or email section

```
email:
  smtp_host: '############'
  smtp_port: 587
  smtp_user: '############'
  smtp_pass: '############'
  enable_tls: true
  require_transport_security: true
  notif_from: '############'
  app_name: '############'
  enable_notifs: false
  notif_for_new_users: false
  client_base_url: '############'
  validation_token_lifetime: 15m
  invite_client_location: 'https://matrix.org'
```

#### What did you expect?
Allow the email to be optionally entered

#### What happened instead?
The email must be entered

### Application version and app store

1.4.34

### Will you send logs?

No

### Are you willing to provide a PR?

No
